package dev.veilshare.core.vault

import dev.veilshare.core.crypto.*
import java.nio.file.Files
import kotlinx.coroutines.test.runTest
import kotlin.test.*

class DeleteFileE2ETest { @Test fun `delete commits catalog before collecting physical blob`()=runTest { val root=Files.createTempDirectory("veil-delete-");val src=Files.createTempFile("delete-",".txt");Files.write(src,"remove me".encodeToByteArray());val c=DesktopProductionCrypto.create();val p=Argon2Policy(Argon2Parameters(8192,1,1));val w=DeleteWrapper(c.cipher);CreateVaultSetUseCase(DesktopVaultSlotStore(root),c.random,c.passwordKdf,w,c.cipher,p,DesktopVaultCatalogBootstrap(root,DesktopProductionCrypto.keyDeriver(),c.cipher)).create(SensitiveChars("111111".toCharArray()),SensitiveChars("222222".toCharArray()));val open=assertIs<DesktopOpenResult.Ready>(DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c.passwordKdf,w,c.cipher,p),DesktopProductionCrypto.keyDeriver(),c.cipher).open(SensitiveChars("111111".toCharArray())));val blobs=DesktopBlobStore(root.resolve("blobs"),open.session.descriptor.blobNamespace);val catalog=DesktopEncryptedCatalogStore(root,open.session.descriptor.vaultId,CatalogCrypto(DesktopProductionCrypto.keyDeriver(),c.cipher));val journal=DesktopVaultJournal(root);val (_,file)=ImportCoordinator(c.random,c.cipher,blobs,catalog,journal,FileKeyWrapping(DesktopProductionCrypto.keyDeriver(),c.cipher)).import(open.session,open.catalog,DesktopImportSource(src));val next=DeleteFileUseCase(c.random,catalog,journal,VaultGarbageCollector(blobs,journal)).delete(open.session,catalog.load(open.session.key()),file.id);assertTrue(next.entries.isEmpty());assertFalse(blobs.exists(file.blobId));open.session.close() } }
private class DeleteWrapper(private val c:AuthenticatedCipher):KeyWrapper {override suspend fun wrap(kek:KeyEncryptionKey,vaultKey:VaultKey,aad:ByteArray)=c.seal(kek.material,vaultKey.material.copy(),aad);override suspend fun unwrap(kek:KeyEncryptionKey,wrapped:SealedBytes,aad:ByteArray)=VaultKey(SensitiveBytes(c.open(kek.material,wrapped,aad)))}
