package dev.veilshare.core.vault

import dev.veilshare.core.crypto.*
import java.nio.file.Files
import kotlinx.coroutines.test.runTest
import kotlin.test.*

class DeleteFaultBoundaryE2ETest { @Test fun `intent durable fault preserves catalog referenced blob after restart`()=runTest { val f=fixture();val before=f.blobs.open(f.a.blobId).readAt(0,Int.MAX_VALUE);assertFailsWith<IllegalStateException>{f.delete(DeleteFaultPoint.IntentDurable)};f.session.close();val r=f.reopen();assertTrue(r.catalog.entries.any{it.id==f.a.id});assertEquals(before.toList(),r.blobs.open(f.a.blobId).readAt(0,Int.MAX_VALUE).toList());r.session.close() }
 @Test fun `catalog durable fault deletes only orphan after restart`()=runTest { val f=fixture();assertFailsWith<IllegalStateException>{f.delete(DeleteFaultPoint.CatalogDurable)};assertTrue(f.blobs.exists(f.a.blobId));f.session.close();val r=f.reopen();assertTrue(r.catalog.entries.none{it.id==f.a.id});val state=AuthenticatedVaultState(r.session.descriptor.vaultId,r.session.descriptor.blobNamespace,r.catalog.entries.filterIsInstance<VaultItem.File>().map{it.blobId}.toSet());VaultRecoveryCoordinator(r.journal,VaultGarbageCollector(r.blobs,r.journal)).reconcileAuthenticated(state);assertFalse(r.blobs.exists(f.a.blobId));assertTrue(r.catalog.entries.any{it.id==f.b.id});r.session.close() }
 private suspend fun fixture():DeleteFixture { val root=Files.createTempDirectory("veil-delete-boundary-");val aFile=Files.createTempFile("A", ".txt");val bFile=Files.createTempFile("B", ".txt");Files.write(aFile,"AAAA".encodeToByteArray());Files.write(bFile,"BBBB".encodeToByteArray());val c=DesktopProductionCrypto.create();val p=Argon2Policy(Argon2Parameters(8192,1,1));val w=BoundaryWrapper(c.cipher);CreateVaultSetUseCase(DesktopVaultSlotStore(root),c.random,c.passwordKdf,w,c.cipher,p,DesktopVaultCatalogBootstrap(root,DesktopProductionCrypto.keyDeriver(),c.cipher)).create(SensitiveChars("111111".toCharArray()),SensitiveChars("222222".toCharArray()));val o=assertIs<DesktopOpenResult.Ready>(open(root,c,p,w));val bs=DesktopBlobStore(root.resolve("blobs"),o.session.descriptor.blobNamespace);val cat=DesktopEncryptedCatalogStore(root,o.session.descriptor.vaultId,CatalogCrypto(DesktopProductionCrypto.keyDeriver(),c.cipher));val j=DesktopVaultJournal(root);val co=ImportCoordinator(c.random,c.cipher,bs,cat,j,FileKeyWrapping(DesktopProductionCrypto.keyDeriver(),c.cipher));val (s1,a)=co.import(o.session,o.catalog,DesktopImportSource(aFile));val (_,b)=co.import(o.session,s1,DesktopImportSource(bFile));return DeleteFixture(root,c,p,w,o.session,cat,j,bs,a,b) }
 private suspend fun open(root:java.nio.file.Path,c:ProductionCryptoComponents,p:Argon2Policy,w:KeyWrapper)=DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c.passwordKdf,w,c.cipher,p),DesktopProductionCrypto.keyDeriver(),c.cipher).open(SensitiveChars("111111".toCharArray()))
 private data class DeleteFixture(val root:java.nio.file.Path,val c:ProductionCryptoComponents,val p:Argon2Policy,val w:KeyWrapper,val session:VaultSession,val catalog:DesktopEncryptedCatalogStore,val journal:DesktopVaultJournal,val blobs:DesktopBlobStore,val a:VaultItem.File,val b:VaultItem.File) { suspend fun delete(point:DeleteFaultPoint)=DeleteFileUseCase(c.random,catalog,journal,VaultGarbageCollector(blobs,journal)){if(it==point)throw IllegalStateException("fault")}.delete(session,catalog.load(session.key()),a.id); suspend fun reopen():Reopened {val c2=DesktopProductionCrypto.create();val o=assertIs<DesktopOpenResult.Ready>(DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c2.passwordKdf,w,c2.cipher,p),DesktopProductionCrypto.keyDeriver(),c2.cipher).open(SensitiveChars("111111".toCharArray())));return Reopened(o.session,o.catalog,DesktopBlobStore(root.resolve("blobs"),o.session.descriptor.blobNamespace),DesktopVaultJournal(root))} }
 private data class Reopened(val session:VaultSession,val catalog:CatalogSnapshot,val blobs:DesktopBlobStore,val journal:DesktopVaultJournal)
}
private class BoundaryWrapper(private val c:AuthenticatedCipher):KeyWrapper {override suspend fun wrap(kek:KeyEncryptionKey,vaultKey:VaultKey,aad:ByteArray)=c.seal(kek.material,vaultKey.material.copy(),aad);override suspend fun unwrap(kek:KeyEncryptionKey,wrapped:SealedBytes,aad:ByteArray)=VaultKey(SensitiveBytes(c.open(kek.material,wrapped,aad)))}
