package dev.veilshare.core.vault

import dev.veilshare.core.crypto.*
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.test.runTest
import java.nio.file.Files
import kotlin.test.*

class ImportCancellationE2ETest { @Test fun `cancellation during streaming leaves no catalog entry and restart cleans journal`()=runTest { val root=Files.createTempDirectory("veil-cancel-");val c=DesktopProductionCrypto.create();val p=Argon2Policy(Argon2Parameters(8192,1,1));val w=CancelWrapper(c.cipher);CreateVaultSetUseCase(DesktopVaultSlotStore(root),c.random,c.passwordKdf,w,c.cipher,p,DesktopVaultCatalogBootstrap(root,DesktopProductionCrypto.keyDeriver(),c.cipher)).create(SensitiveChars("111111".toCharArray()),SensitiveChars("222222".toCharArray()));val opened=assertIs<DesktopOpenResult.Ready>(DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c.passwordKdf,w,c.cipher,p),DesktopProductionCrypto.keyDeriver(),c.cipher).open(SensitiveChars("111111".toCharArray())));val journal=DesktopVaultJournal(root);val source=object:ImportSource {override val displayName="cancel.txt";override val mimeHint:String?="text/plain";override val sizeHint:Long?=null;override suspend fun openRead()=object:ImportReadHandle {var reads=0;override suspend fun read(maxBytes:Int)=if(reads++==0)ByteArray(1024){7}else throw CancellationException("test cancel");override suspend fun close()=Unit}};val coordinator=ImportCoordinator(c.random,c.cipher,DesktopBlobStore(root.resolve("blobs"),opened.session.descriptor.blobNamespace),DesktopEncryptedCatalogStore(root,opened.session.descriptor.vaultId,CatalogCrypto(DesktopProductionCrypto.keyDeriver(),c.cipher)),journal,FileKeyWrapping(DesktopProductionCrypto.keyDeriver(),c.cipher));assertFailsWith<CancellationException>{coordinator.import(opened.session,opened.catalog,source)};opened.session.close();val c2=DesktopProductionCrypto.create();val re=assertIs<DesktopOpenResult.Ready>(DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c2.passwordKdf,CancelWrapper(c2.cipher),c2.cipher,p),DesktopProductionCrypto.keyDeriver(),c2.cipher).open(SensitiveChars("111111".toCharArray())));val j2=DesktopVaultJournal(root);val bs=DesktopBlobStore(root.resolve("blobs"),re.session.descriptor.blobNamespace);VaultRecoveryCoordinator(j2,VaultGarbageCollector(bs,j2)).reconcileAuthenticated(AuthenticatedVaultState(re.session.descriptor.vaultId,re.session.descriptor.blobNamespace,emptySet()));assertTrue(re.catalog.entries.isEmpty());assertTrue(j2.entries().isEmpty());assertTrue(bs.listIds().isEmpty());re.session.close() } }
private class CancelWrapper(private val c:AuthenticatedCipher):KeyWrapper {override suspend fun wrap(kek:KeyEncryptionKey,vaultKey:VaultKey,aad:ByteArray)=c.seal(kek.material,vaultKey.material.copy(),aad);override suspend fun unwrap(kek:KeyEncryptionKey,wrapped:SealedBytes,aad:ByteArray)=VaultKey(SensitiveBytes(c.open(kek.material,wrapped,aad)))}
