package dev.veilshare.core.vault

import dev.veilshare.core.crypto.*
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.test.runTest
import java.nio.file.Files
import kotlin.test.*

class ImportCommitPointE2ETest { @Test fun `cancellation after durable catalog preserves import on restart`()=runTest { val root=Files.createTempDirectory("veil-cancel-commit-");val src=Files.createTempFile("commit-", ".txt");val bytes="durable after cancel".encodeToByteArray();Files.write(src,bytes);val c=DesktopProductionCrypto.create();val p=Argon2Policy(Argon2Parameters(8192,1,1));val w=CommitWrapper(c.cipher);CreateVaultSetUseCase(DesktopVaultSlotStore(root),c.random,c.passwordKdf,w,c.cipher,p,DesktopVaultCatalogBootstrap(root,DesktopProductionCrypto.keyDeriver(),c.cipher)).create(SensitiveChars("111111".toCharArray()),SensitiveChars("222222".toCharArray()));val o=assertIs<DesktopOpenResult.Ready>(open(root,c,p,w));val bs=DesktopBlobStore(root.resolve("blobs"),o.session.descriptor.blobNamespace);val j=DesktopVaultJournal(root);assertFailsWith<CancellationException>{ImportCoordinator(c.random,c.cipher,bs,DesktopEncryptedCatalogStore(root,o.session.descriptor.vaultId,CatalogCrypto(DesktopProductionCrypto.keyDeriver(),c.cipher)),j,FileKeyWrapping(DesktopProductionCrypto.keyDeriver(),c.cipher)){if(it==ImportFaultPoint.CatalogDurable)throw CancellationException("late")}.import(o.session,o.catalog,DesktopImportSource(src))};o.session.close();val c2=DesktopProductionCrypto.create();val re=assertIs<DesktopOpenResult.Ready>(open(root,c2,p,CommitWrapper(c2.cipher)));val file=assertIs<VaultItem.File>(re.catalog.entries.single());assertTrue(DesktopBlobStore(root.resolve("blobs"),re.session.descriptor.blobNamespace).exists(file.blobId));re.session.close() }
 private suspend fun open(root:java.nio.file.Path,c:ProductionCryptoComponents,p:Argon2Policy,w:KeyWrapper)=DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c.passwordKdf,w,c.cipher,p),DesktopProductionCrypto.keyDeriver(),c.cipher).open(SensitiveChars("111111".toCharArray())) }
private class CommitWrapper(private val c:AuthenticatedCipher):KeyWrapper {override suspend fun wrap(kek:KeyEncryptionKey,vaultKey:VaultKey,aad:ByteArray)=c.seal(kek.material,vaultKey.material.copy(),aad);override suspend fun unwrap(kek:KeyEncryptionKey,wrapped:SealedBytes,aad:ByteArray)=VaultKey(SensitiveBytes(c.open(kek.material,wrapped,aad)))}
