package dev.veilshare.core.vault

import dev.veilshare.core.crypto.*
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.test.runTest
import java.nio.file.Files
import kotlin.test.*

class ImportPostFinalizeCancellationTest { @Test fun `cancellation after durable blob becomes confirmed orphan after restart`()=runTest { val root=Files.createTempDirectory("veil-cancel-final-");val src=Files.createTempFile("final-", ".txt");Files.write(src,"final but not catalog".encodeToByteArray());val c=DesktopProductionCrypto.create();val p=Argon2Policy(Argon2Parameters(8192,1,1));val w=FinalizeWrapper(c.cipher);CreateVaultSetUseCase(DesktopVaultSlotStore(root),c.random,c.passwordKdf,w,c.cipher,p,DesktopVaultCatalogBootstrap(root,DesktopProductionCrypto.keyDeriver(),c.cipher)).create(SensitiveChars("111111".toCharArray()),SensitiveChars("222222".toCharArray()));val o=assertIs<DesktopOpenResult.Ready>(open(root,c,p,w));val bs=DesktopBlobStore(root.resolve("blobs"),o.session.descriptor.blobNamespace);val j=DesktopVaultJournal(root);assertFailsWith<CancellationException>{ImportCoordinator(c.random,c.cipher,bs,DesktopEncryptedCatalogStore(root,o.session.descriptor.vaultId,CatalogCrypto(DesktopProductionCrypto.keyDeriver(),c.cipher)),j,FileKeyWrapping(DesktopProductionCrypto.keyDeriver(),c.cipher)){if(it==ImportFaultPoint.BlobDurableBeforeCatalog)throw CancellationException("precommit")}.import(o.session,o.catalog,DesktopImportSource(src))};o.session.close();assertEquals(1,bs.listIds().size);val c2=DesktopProductionCrypto.create();val re=assertIs<DesktopOpenResult.Ready>(open(root,c2,p,FinalizeWrapper(c2.cipher)));val jj=DesktopVaultJournal(root);val newBs=DesktopBlobStore(root.resolve("blobs"),re.session.descriptor.blobNamespace);VaultRecoveryCoordinator(jj,VaultGarbageCollector(newBs,jj)).reconcileAuthenticated(AuthenticatedVaultState(re.session.descriptor.vaultId,re.session.descriptor.blobNamespace,emptySet()));assertTrue(re.catalog.entries.isEmpty());assertTrue(newBs.listIds().isEmpty());assertTrue(jj.entries().isEmpty());re.session.close() }
 private suspend fun open(root:java.nio.file.Path,c:ProductionCryptoComponents,p:Argon2Policy,w:KeyWrapper)=DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c.passwordKdf,w,c.cipher,p),DesktopProductionCrypto.keyDeriver(),c.cipher).open(SensitiveChars("111111".toCharArray())) }
private class FinalizeWrapper(private val c:AuthenticatedCipher):KeyWrapper {override suspend fun wrap(kek:KeyEncryptionKey,vaultKey:VaultKey,aad:ByteArray)=c.seal(kek.material,vaultKey.material.copy(),aad);override suspend fun unwrap(kek:KeyEncryptionKey,wrapped:SealedBytes,aad:ByteArray)=VaultKey(SensitiveBytes(c.open(kek.material,wrapped,aad)))}
