package dev.veilshare.core.vault

import dev.veilshare.core.crypto.*
import dev.veilshare.core.model.BlobId
import java.nio.file.Files
import kotlinx.coroutines.test.runTest
import kotlin.test.*

class PersistentRecoveryE2ETest {
 @Test fun `physical pre catalog crash removes only finalized orphan after authenticated reopen`()=runTest {
  val root=Files.createTempDirectory("veil-recovery-pre-");val c=DesktopProductionCrypto.create();val p=Argon2Policy(Argon2Parameters(8192,1,1));val w=RecoveryWrapper(c.cipher);CreateVaultSetUseCase(DesktopVaultSlotStore(root),c.random,c.passwordKdf,w,c.cipher,p,DesktopVaultCatalogBootstrap(root,DesktopProductionCrypto.keyDeriver(),c.cipher)).create(SensitiveChars("111111".toCharArray()),SensitiveChars("222222".toCharArray()))
  val opened=assertIs<DesktopOpenResult.Ready>(DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c.passwordKdf,w,c.cipher,p),DesktopProductionCrypto.keyDeriver(),c.cipher).open(SensitiveChars("111111".toCharArray())));val ns=opened.session.descriptor.blobNamespace;var sent=false;val orphanKey=FileKeyGenerator(c.random).generate();val orphan=EncryptedBlobWriter(c.cipher,c.random).write({ if(sent) ByteArray(0) else "orphan".encodeToByteArray().also{sent=true} },DesktopBlobStore(root.resolve("blobs"),ns).create(),orphanKey,"orphan-context".encodeToByteArray()).blobId;orphanKey.material.close();DesktopVaultJournal(root).put(JournalEntry(TransactionId("pre"),TransactionState.VERIFYING,setOf(orphan),ns));opened.session.close()
  val c2=DesktopProductionCrypto.create();val reopened=assertIs<DesktopOpenResult.Ready>(DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c2.passwordKdf,RecoveryWrapper(c2.cipher),c2.cipher,p),DesktopProductionCrypto.keyDeriver(),c2.cipher).open(SensitiveChars("111111".toCharArray())));val journal=DesktopVaultJournal(root);val blobStore=DesktopBlobStore(root.resolve("blobs"),reopened.session.descriptor.blobNamespace);val state=AuthenticatedVaultState(reopened.session.descriptor.vaultId,reopened.session.descriptor.blobNamespace,reopened.catalog.entries.filterIsInstance<VaultItem.File>().map{it.blobId}.toSet());val recovery=VaultRecoveryCoordinator(journal,VaultGarbageCollector(blobStore,journal));recovery.reconcileAuthenticated(state);assertFalse(blobStore.exists(orphan));assertTrue(journal.entries().isEmpty());recovery.reconcileAuthenticated(state);assertFalse(blobStore.exists(orphan));reopened.session.close()
 }
 @Test fun `physical post catalog crash preserves referenced blob and clears stale journal`()=runTest {
  val root=Files.createTempDirectory("veil-recovery-post-");val source=Files.createTempFile("post-", ".txt");val plain="post durable".encodeToByteArray();Files.write(source,plain);val c=DesktopProductionCrypto.create();val p=Argon2Policy(Argon2Parameters(8192,1,1));val w=RecoveryWrapper(c.cipher);CreateVaultSetUseCase(DesktopVaultSlotStore(root),c.random,c.passwordKdf,w,c.cipher,p,DesktopVaultCatalogBootstrap(root,DesktopProductionCrypto.keyDeriver(),c.cipher)).create(SensitiveChars("111111".toCharArray()),SensitiveChars("222222".toCharArray()));val open=assertIs<DesktopOpenResult.Ready>(DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c.passwordKdf,w,c.cipher,p),DesktopProductionCrypto.keyDeriver(),c.cipher).open(SensitiveChars("111111".toCharArray())));val bs=DesktopBlobStore(root.resolve("blobs"),open.session.descriptor.blobNamespace);val j=DesktopVaultJournal(root);val (_,file)=ImportCoordinator(c.random,c.cipher,bs,DesktopEncryptedCatalogStore(root,open.session.descriptor.vaultId,CatalogCrypto(DesktopProductionCrypto.keyDeriver(),c.cipher)),j,FileKeyWrapping(DesktopProductionCrypto.keyDeriver(),c.cipher)).import(open.session,open.catalog,DesktopImportSource(source));j.put(JournalEntry(TransactionId("stale"),TransactionState.VERIFYING,setOf(file.blobId),open.session.descriptor.blobNamespace));open.session.close()
  val c2=DesktopProductionCrypto.create();val re=assertIs<DesktopOpenResult.Ready>(DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c2.passwordKdf,RecoveryWrapper(c2.cipher),c2.cipher,p),DesktopProductionCrypto.keyDeriver(),c2.cipher).open(SensitiveChars("111111".toCharArray())));val store=DesktopBlobStore(root.resolve("blobs"),re.session.descriptor.blobNamespace);val jj=DesktopVaultJournal(root);val state=AuthenticatedVaultState(re.session.descriptor.vaultId,re.session.descriptor.blobNamespace,re.catalog.entries.filterIsInstance<VaultItem.File>().map{it.blobId}.toSet());VaultRecoveryCoordinator(jj,VaultGarbageCollector(store,jj)).reconcileAuthenticated(state);assertTrue(store.exists(file.blobId));assertTrue(jj.entries().isEmpty());re.session.close()
 }
}
private class RecoveryWrapper(private val c:AuthenticatedCipher):KeyWrapper {override suspend fun wrap(kek:KeyEncryptionKey,vaultKey:VaultKey,aad:ByteArray)=c.seal(kek.material,vaultKey.material.copy(),aad);override suspend fun unwrap(kek:KeyEncryptionKey,wrapped:SealedBytes,aad:ByteArray)=VaultKey(SensitiveBytes(c.open(kek.material,wrapped,aad)))}
