package dev.veilshare.core.vault

import dev.veilshare.core.crypto.*
import java.nio.file.Files
import kotlinx.coroutines.test.runTest
import kotlin.test.*

class PersistentCorruptionSafetyTest { @Test fun `catalog ciphertext corruption returns corrupt while retaining namespaced blob`()=runTest {
 val root=Files.createTempDirectory("veil-corrupt-cat-");val src=Files.createTempFile("A", ".txt");Files.write(src,"safe-content".encodeToByteArray());val c=DesktopProductionCrypto.create();val p=Argon2Policy(Argon2Parameters(8192,1,1));val w=CorruptWrapper(c.cipher);CreateVaultSetUseCase(DesktopVaultSlotStore(root),c.random,c.passwordKdf,w,c.cipher,p,DesktopVaultCatalogBootstrap(root,DesktopProductionCrypto.keyDeriver(),c.cipher)).create(SensitiveChars("111111".toCharArray()),SensitiveChars("222222".toCharArray()));val opened=assertIs<DesktopOpenResult.Ready>(open(root,c,p,w,"111111"));val blobs=DesktopBlobStore(root.resolve("blobs"),opened.session.descriptor.blobNamespace);val (_,f)=ImportCoordinator(c.random,c.cipher,blobs,DesktopEncryptedCatalogStore(root,opened.session.descriptor.vaultId,CatalogCrypto(DesktopProductionCrypto.keyDeriver(),c.cipher)),DesktopVaultJournal(root),FileKeyWrapping(DesktopProductionCrypto.keyDeriver(),c.cipher)).import(opened.session,opened.catalog,DesktopImportSource(src));val before=Files.readAllBytes(Files.walk(root.resolve("blobs")).filter{Files.isRegularFile(it)}.findFirst().get());val catalog=root.resolve("catalogs").resolve(opened.session.descriptor.vaultId.value.take(24)+".vcat");Files.write(catalog,Files.readAllBytes(catalog).also{it[it.lastIndex]=(it.last().toInt()xor 1).toByte()});opened.session.close();assertIs<DesktopOpenResult.Corrupt>(open(root,c,p,w,"111111"));assertTrue(blobs.exists(f.blobId));assertEquals(before.toList(),Files.readAllBytes(Files.walk(root.resolve("blobs")).filter{Files.isRegularFile(it)}.findFirst().get()).toList());assertIs<DesktopOpenResult.Ready>(open(root,c,p,w,"222222"))
 }
 @Test fun `corrupt journal cannot authorize blob deletion`()=runTest { val root=Files.createTempDirectory("veil-corrupt-journal-");val journal=DesktopVaultJournal(root);journal.put(JournalEntry(TransactionId("x"),TransactionState.PREPARING,emptySet(),"opaque"));val path=root.resolve("state").resolve("j-9c4e0a.bin");Files.write(path,byteArrayOf(1));assertFailsWith<Exception>{DesktopVaultJournal(root)} }
 private suspend fun open(root:java.nio.file.Path,c:ProductionCryptoComponents,p:Argon2Policy,w:KeyWrapper,pin:String)=DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c.passwordKdf,w,c.cipher,p),DesktopProductionCrypto.keyDeriver(),c.cipher).open(SensitiveChars(pin.toCharArray()))
}
private class CorruptWrapper(private val c:AuthenticatedCipher):KeyWrapper {override suspend fun wrap(kek:KeyEncryptionKey,vaultKey:VaultKey,aad:ByteArray)=c.seal(kek.material,vaultKey.material.copy(),aad);override suspend fun unwrap(kek:KeyEncryptionKey,wrapped:SealedBytes,aad:ByteArray)=VaultKey(SensitiveBytes(c.open(kek.material,wrapped,aad)))}
