package dev.veilshare.core.vault

import dev.veilshare.core.crypto.*
import java.nio.file.Files
import kotlinx.coroutines.test.runTest
import kotlin.test.*

class RealDecoyIsolationE2ETest { @Test fun `real and decoy files remain isolated after process restart`()=runTest {
 val root=Files.createTempDirectory("veil-isolation-");val real=Files.createTempFile("REAL_ONLY_FILE_111",".txt");val decoy=Files.createTempFile("DECOY_ONLY_FILE_222",".txt");Files.write(real,"REAL_ONLY_CONTENT_111".encodeToByteArray());Files.write(decoy,"DECOY_ONLY_CONTENT_222".encodeToByteArray());val c=DesktopProductionCrypto.create();val p=Argon2Policy(Argon2Parameters(8192,1,1));val w=IsolationWrapper(c.cipher);CreateVaultSetUseCase(DesktopVaultSlotStore(root),c.random,c.passwordKdf,w,c.cipher,p,DesktopVaultCatalogBootstrap(root,DesktopProductionCrypto.keyDeriver(),c.cipher)).create(SensitiveChars("000123".toCharArray()),SensitiveChars("000124".toCharArray()))
 suspend fun add(pin:String,file:java.nio.file.Path){val r=assertIs<DesktopOpenResult.Ready>(DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c.passwordKdf,w,c.cipher,p),DesktopProductionCrypto.keyDeriver(),c.cipher).open(SensitiveChars(pin.toCharArray())));ImportCoordinator(c.random,c.cipher,DesktopBlobStore(root.resolve("blobs"),r.session.descriptor.blobNamespace),DesktopEncryptedCatalogStore(root,r.session.descriptor.vaultId,CatalogCrypto(DesktopProductionCrypto.keyDeriver(),c.cipher)),DesktopVaultJournal(root),FileKeyWrapping(DesktopProductionCrypto.keyDeriver(),c.cipher)).import(r.session,r.catalog,DesktopImportSource(file));r.session.close()};add("000123",real);add("000124",decoy)
 val c2=DesktopProductionCrypto.create();suspend fun open(pin:String)=assertIs<DesktopOpenResult.Ready>(DesktopVaultRepository(root,UnlockVaultUseCase(DesktopVaultSlotStore(root),c2.passwordKdf,IsolationWrapper(c2.cipher),c2.cipher,p),DesktopProductionCrypto.keyDeriver(),c2.cipher).open(SensitiveChars(pin.toCharArray())))
 val rr=open("000123");assertEquals(listOf("REAL_ONLY_FILE_111"+real.fileName.toString().substringAfter("REAL_ONLY_FILE_111")),rr.catalog.entries.map{it.displayName});val rgc=VaultGarbageCollector(DesktopBlobStore(root.resolve("blobs"),rr.session.descriptor.blobNamespace),DesktopVaultJournal(root));rgc.collect(rgc.scan(AuthenticatedVaultState(rr.session.descriptor.vaultId,rr.session.descriptor.blobNamespace,rr.catalog.entries.filterIsInstance<VaultItem.File>().map{it.blobId}.toSet())));rr.session.close();val dd=open("000124");assertEquals(listOf("DECOY_ONLY_FILE_222"+decoy.fileName.toString().substringAfter("DECOY_ONLY_FILE_222")),dd.catalog.entries.map{it.displayName});val dgc=VaultGarbageCollector(DesktopBlobStore(root.resolve("blobs"),dd.session.descriptor.blobNamespace),DesktopVaultJournal(root));dgc.collect(dgc.scan(AuthenticatedVaultState(dd.session.descriptor.vaultId,dd.session.descriptor.blobNamespace,dd.catalog.entries.filterIsInstance<VaultItem.File>().map{it.blobId}.toSet())));dd.session.close()
 val bytes=ArrayList<Byte>();Files.walk(root).use{it.filter{p->Files.isRegularFile(p)}.forEach{p->Files.readAllBytes(p).forEach(bytes::add)}};val all=bytes.toByteArray();listOf("REAL_ONLY_FILE_111","REAL_ONLY_CONTENT_111","DECOY_ONLY_FILE_222","DECOY_ONLY_CONTENT_222").forEach{s->assertFalse(all.has(s.encodeToByteArray()))}
} }
private class IsolationWrapper(private val c:AuthenticatedCipher):KeyWrapper {override suspend fun wrap(kek:KeyEncryptionKey,vaultKey:VaultKey,aad:ByteArray)=c.seal(kek.material,vaultKey.material.copy(),aad);override suspend fun unwrap(kek:KeyEncryptionKey,wrapped:SealedBytes,aad:ByteArray)=VaultKey(SensitiveBytes(c.open(kek.material,wrapped,aad)))}
private fun ByteArray.has(s:ByteArray)=(0..size-s.size).any{copyOfRange(it,it+s.size).contentEquals(s)}
